services:
  fastapi-app:
    build:
      context: .
    ports:
      - "9000:9000"
    volumes:
      - ./my_todo_app:/app/my_todo_app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: uvicorn my_todo_app.main:app --host 0.0.0.0 --port 9000 --reload