services:
  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: uvicorn my_todo_app.main:app --host 0.0.0.0 --port 8000 --reload