services:
  fastapi-app:
    build:
      context: ./my_todo_app
    ports:
      - "9000:9000"
    volumes:
      - ./my_todo_app:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app       # 👈 여기가 핵심!
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload